### ISSUE TITLE
Local Package Source not working

### ISSUE THREAD

**Issue by Vijay-Nirmal** [pcislo/vscode-nuget-gallery#13]
Can't refer packages from Local PC

I have tried the following formats

```
{"name": "Local Packages","url": "C:/Local Packages/"}
```

```
{"name": "Local Packages","url": "C:\Local Packages\"}
```

```
{"name": "Local Packages","url": "C:\\Local Packages\\"}
```

```
{"name": "Local Packages","url": "file:///C:/Local%20Packages/"}
```

**Comment by pcislo** [comment]
Hi, packages from folders are not supported. In order to use your own private nuget packages you need to use NuGet hosting, for example Azure Artifacts.

**Comment by Vijay-Nirmal** [comment]
We have Azure Artifacts but for testing purposes we are using local packages.

Is there any issue in supporting this feature?

**Comment by pcislo** [comment]
This extension uses webview API and I can't directly read directories from there as they aren't available in webviews due to the security reasons. There are some workarounds of course, but they require more effort to implement. Besides, the extension has no knowledge about filtering, extracting info from nuget packages as everything is done in the nuget server right now.

I'm also wondering if some kind of local server that will behave like a proxy between extension and packages in folder will do the job in your case?

**Comment by Vijay-Nirmal** [comment]
Do you mean I have to create a Nuget Server?

I don't think it is a proper solution because (1) its not straight forward (2) my whole team should host there own Nuget Server

**Comment by pcislo** [comment]
Not exactly create, but rather use some of ready solutions. You can run it on your server that should be accessible to the whole team and add shared folders for your team to add packages there. This way you need only one nuget server for the whole team.

It's not a proper solution, but a way of using packages from local folders with the current version of the extension.
